# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.hostname   = 'lockrun-berkshelf'
  config.vm.box        = 'opscode-ubuntu-12.04'
  config.vm.box_url    = 'https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box'
  config.ssh.max_tries = 40
  config.ssh.timeout   = 120

  config.vm.network :private_network, ip: '33.33.33.10'


  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      'recipe[lockrun::default]'
    ]
  end
end
